baseURL = 'https://madhurahuja.github.io/create-claude-context/'
languageCode = 'en-us'
title = 'create-claude-context CLI'
theme = ["lotusdocs"]

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"

[params]
  description = "A beautiful interactive CLI to quickly bootstrap Claude projects."
  docs = "docs"
  
[markup]
  [markup.goldmark.renderer]
    unsafe = true
